# Change these first
owner: hualvwang # Your GitHub organization or username, where this repository lives
repo: web-status # The name of this repository

runner: "[self-hosted, Linux, X64]"

# user-agent: your-github-username

sites:
  - name: hualv
    url: https://www.66law.cn
  - name: lvtu
    url: https://www.64365.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hualv.com
  # baseUrl: /your-repo-name
  logoUrl: https://css.66law.cn/images/v/logo.png
  name: HuaLv Status
  introTitle: "uptime monitor and status page for hualv."
  introMessage: "This is a page that can provide real-time information on the uptime and status of websites."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
